name: Scorecard security check
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  push:
    branches:
      - main
permissions:
  contents: read
  security-events: write
jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif

      - name: Upload Scorecard analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
